### ISSUE TITLE
Link for 1.8 The Binomial Expansion.pdf not working on .io site

### ISSUE THREAD

**Issue by WyrdWyn4** [brainstormerjr/A-Level-Notes#1]
Hi Harold,

It seems that the link for 1.8 The Binomial Expansion.pdf on your website https://brainstormerjr.github.io/A-Level-Notes/ is not working. 

I received the following on my screen when I opened it.

![image](https://user-images.githubusercontent.com/66204156/160915430-0af5340b-bc19-4818-85a2-99a6f8010141.png)

I've got the PDF from here though, but I thought I'd let you know for your reference.

Cheers,
Waleed

**Comment by brainstormerjr** [comment]
Error caused by a typo in the file name, and the pdf was empty as well XD

Hopefully patched :)
